In [1]:
import numpy as np

In [2]:
grid = np.arange(25).reshape(5,5)
print(grid)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [3]:
x = 3
y = 3
x = list(range(x-1, x+2))
y = list(range(y-1, y+2))

In [16]:
class Grid:
    def __init__(self, inparr):
        self.shape = inparr.shape
        self.current_state = inparr
        self.next_state = np.zeros_like(inparr)
        self.num_nghbr_state = np.zeros_like(inparr)


    def check_nghbrs(self, i):
        x, y = i
        num_alive = 0
        for r in range(x-1, x+2):
            for c in range(y-1, y+2):
                try:
                    if self.current_state[r][c] == 1 and (r, c) != (x, y) and (r >= 0) and (c >= 0) :
                        num_alive += 1
                except IndexError:
                    pass
                # print(i, '->', (r, c), 'current num alive:', num_alive) #useful for debugging

        return num_alive
    
    def update_stage(self, itr = 1):
        print(self.current_state)
        for it in range(itr):
            for x in range(self.shape[0]):
                for y in range(self.shape[1]):
                    pnt_stt = self.current_state[x][y]
                    pos = (x, y)
                    alive_nghbr = self.check_nghbrs(pos)
                    self.num_nghbr_state[x][y] = alive_nghbr

                    #update block
                    match pnt_stt:
                        case 1:
                            if (alive_nghbr < 2) or (alive_nghbr > 3):
                                self.next_state[x][y] = 0
                            else:
                                self.next_state[x][y] = 1
                        case 0:
                            if alive_nghbr == 3:
                                self.next_state[x][y] = 1
                            else:
                                self.next_state[x][y] = 0

            # print(self.num_nghbr_state) #useful for debugging
            print(self.next_state)
            self.current_state = np.copy(self.next_state)
        return self.current_state
        

In [17]:
ar_map = np.array([
    [0, 0, 0, 0, 0],
    [0, 1, 1, 1, 0],
    [0, 0, 1, 0, 1],
    [0, 1, 0, 1, 0],
    [0, 0, 0, 1, 1]
])

In [18]:
ar_map.shape

(5, 5)

In [19]:
grid = Grid(ar_map)

In [20]:
grid.next_state

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [21]:
grid.current_state

array([[0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0],
       [0, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [0, 0, 0, 1, 1]])

In [22]:
grid.update_stage()

[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 0 1 0 1]
 [0 1 0 1 0]
 [0 0 0 1 1]]
[[0 0 1 0 0]
 [0 1 1 1 0]
 [0 0 0 0 1]
 [0 0 0 0 0]
 [0 0 1 1 1]]


array([[0, 0, 1, 0, 0],
       [0, 1, 1, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0],
       [0, 0, 1, 1, 1]])

In [23]:
grid.update_stage()

[[0 0 1 0 0]
 [0 1 1 1 0]
 [0 0 0 0 1]
 [0 0 0 0 0]
 [0 0 1 1 1]]
[[0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 1 1 0]
 [0 0 0 0 1]
 [0 0 0 1 0]]


array([[0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 0, 1, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0]])

In [24]:
random_array = np.random.randint(0, 2, size=(28, 28))

In [25]:
print(random_array)

[[0 0 0 1 1 1 0 1 1 1 1 1 0 0 0 0 0 0 0 1 1 0 0 0 0 1 1 0]
 [0 1 1 1 1 1 0 1 1 1 0 0 1 0 0 1 1 1 0 1 1 0 1 1 1 1 0 1]
 [1 1 1 1 1 0 1 1 0 0 0 1 0 1 0 0 1 0 1 0 1 0 0 0 1 0 1 1]
 [1 0 1 0 0 0 1 1 1 1 1 0 1 0 0 0 0 0 1 1 1 0 1 0 0 0 0 0]
 [1 0 1 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 0 0 0 1 1 0 1 1 0 1]
 [0 1 1 0 0 1 0 0 0 0 0 1 1 1 0 1 1 0 0 0 0 1 1 1 1 1 0 1]
 [1 1 0 0 0 0 0 0 0 1 1 1 1 0 1 0 0 0 0 0 0 0 1 0 0 1 1 1]
 [0 0 0 0 1 1 1 0 0 1 0 1 1 1 0 1 0 0 0 0 0 0 1 0 0 1 0 1]
 [0 1 1 1 1 0 0 0 0 1 0 1 0 0 0 1 0 0 0 0 0 1 1 0 0 0 1 1]
 [0 1 0 1 1 0 1 1 1 0 1 1 0 1 0 1 1 1 0 0 0 1 0 0 0 1 1 0]
 [0 1 1 1 0 1 1 1 1 1 0 0 0 0 1 1 0 1 1 1 0 0 1 0 1 1 0 1]
 [0 0 0 1 0 1 1 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1]
 [0 1 1 1 1 0 1 0 0 1 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1 1 0]
 [0 1 0 0 1 1 1 1 0 1 1 1 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 1]
 [1 0 0 1 0 1 0 1 0 1 1 1 0 0 1 0 0 0 1 0 1 1 0 1 1 1 0 1]
 [1 0 0 0 1 1 1 1 0 0 0 1 1 0 0 0 0 0 1 1 1 1 1 0 1 1 1 0]
 [0 0 1 1 0 0 0 0 0 0 1 1 0 1 1 0 0 1 1 1 1 0 1 0 0 1 0 

In [26]:
rdn_grid = Grid(random_array)

In [27]:
rdn_grid.update_stage(3)

[[0 0 0 1 1 1 0 1 1 1 1 1 0 0 0 0 0 0 0 1 1 0 0 0 0 1 1 0]
 [0 1 1 1 1 1 0 1 1 1 0 0 1 0 0 1 1 1 0 1 1 0 1 1 1 1 0 1]
 [1 1 1 1 1 0 1 1 0 0 0 1 0 1 0 0 1 0 1 0 1 0 0 0 1 0 1 1]
 [1 0 1 0 0 0 1 1 1 1 1 0 1 0 0 0 0 0 1 1 1 0 1 0 0 0 0 0]
 [1 0 1 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 0 0 0 1 1 0 1 1 0 1]
 [0 1 1 0 0 1 0 0 0 0 0 1 1 1 0 1 1 0 0 0 0 1 1 1 1 1 0 1]
 [1 1 0 0 0 0 0 0 0 1 1 1 1 0 1 0 0 0 0 0 0 0 1 0 0 1 1 1]
 [0 0 0 0 1 1 1 0 0 1 0 1 1 1 0 1 0 0 0 0 0 0 1 0 0 1 0 1]
 [0 1 1 1 1 0 0 0 0 1 0 1 0 0 0 1 0 0 0 0 0 1 1 0 0 0 1 1]
 [0 1 0 1 1 0 1 1 1 0 1 1 0 1 0 1 1 1 0 0 0 1 0 0 0 1 1 0]
 [0 1 1 1 0 1 1 1 1 1 0 0 0 0 1 1 0 1 1 1 0 0 1 0 1 1 0 1]
 [0 0 0 1 0 1 1 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1]
 [0 1 1 1 1 0 1 0 0 1 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1 1 0]
 [0 1 0 0 1 1 1 1 0 1 1 1 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 1]
 [1 0 0 1 0 1 0 1 0 1 1 1 0 0 1 0 0 0 1 0 1 1 0 1 1 1 0 1]
 [1 0 0 0 1 1 1 1 0 0 0 1 1 0 0 0 0 0 1 1 1 1 1 0 1 1 1 0]
 [0 0 1 1 0 0 0 0 0 0 1 1 0 1 1 0 0 1 1 1 1 0 1 0 0 1 0 

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
        1, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 1],
       [1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0,
        0, 0, 1, 1, 0, 1],
       [1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
        1, 1, 1, 0, 0, 1],
       [0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 1, 1],
       [0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
        0, 0, 0, 1, 1, 1],
       [1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 1, 1, 1],
       [1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
        1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
        0, 1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 